# Generated by Django 4.0.1 on 2022-01-24 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='login_user',
        ),
    ]
