# Generated by Django 4.0.1 on 2022-01-31 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_login_login_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_user',
            name='passw',
            field=models.CharField(max_length=255),
        ),
    ]
