# Generated by Django 4.0.1 on 2022-02-28 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_demodb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demodb',
            old_name='eamil',
            new_name='email',
        ),
    ]
